### ISSUE TITLE
can't compile example

### ISSUE THREAD

**Issue by matri** [minimoog/QTweetLib#1]
Hi,

Thank you for the great qt twitter library, i'd like to have a look at the example on Mac OSx 10.6.4 and QT 4.7, but the example can't be compiled, there are several errors which look like these:

Undefined symbols:
  "OAuth::OAuth(QObject_)", referenced from:
      OAuthTwitter::OAuthTwitter(QObject_)in oauthtwitter.o
      OAuthTwitter::OAuthTwitter(QObject_)in oauthtwitter.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *_\* [exampletest.app/Contents/MacOS/exampletest] Error 1

Is there any special modification should i take before compilation?
Thank you!

Regards,
Matri

**Comment by minimoog** [comment]
exampletest shoudn't be there, it was quick internal setup just for quick test. I need to do some reordering of folders and qmake .pro files.

Anyway compile try compiling 'only' exampletest, QTweetLib sources if you notice are already in the exampletest.pro file. Tell me if it's ok. You will also need OAuth token oauth.cpp lines 26 and 27.

I don't have Mac OS X, so I cannot test on that OS.

Thanks for reporting,
Toni

**Comment by matri** [comment]
Sorry for the late, just get the latest source code, the example project compiles normally and i could see the demo now, thanks a lot, i'll see what i can do with this library :).

Regards,
Matri
