### ISSUE TITLE
Can't compile sample projects

### ISSUE THREAD

**Issue by ghost** [minimoog/QTweetLib#18]
Hi, first of all let me thank you for this amazing library! However, it seems like I can't compile ANY of the examples provided with the source code. I had to change from -lqtweetlib to -lQTweetLib in unix, but now I'm getting the following errors:

/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValueRef::toArray() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonValue::type() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonDocument::isArray() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonValue::toObject() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonArray::at(int) const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonArray::operator[](int) const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValueRef::toObject() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonValue::toString() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValue::toArray() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonArray::operator[](int)'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValue::toBool() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonArray::~QJsonArray()'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonObject::~QJsonObject()'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonDocument::isObject() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonArray::isEmpty() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonObject::contains(QString const&) const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValue::~QJsonValue()'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonArray::size() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonDocument::~QJsonDocument()'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonDocument::fromJson(QByteArray const&, QJsonParseError_)'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonObject::operator[](QString const&)'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonDocument::object() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonValueRef::toValue() const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonDocument::array() const'
/usr/local/lib/libQTweetLib.so: undefined reference to `QJsonObject::value(QString const&) const'
/usr/local/lib/libQTweetLib.so: undefined reference to`QJsonValue::toDouble() const'
collect2: error: ld returned 1 exit status
make: *_\* [geosearch] Error 1

What is the problem? :S

**Comment by jefferai** [comment]
What version of QTweetLib? What version of QJson?

**Comment by ghost** [comment]
I think it's the latest... I did the following steps:

git clone https://github.com/minimoog/QTweetLib.git
mkdir build
cd build
cmake ..
make 
sudo make install

Repeated the same steps for Qjson.

**Comment by ghost** [comment]
Fixed, it's now working properly. Just needed to download the release version instead of cloning the repository.

**Comment by jefferai** [comment]
I'm guessing that the examples haven't been updated to match the new API.

**Comment by minimoog** [comment]
QTweetLib doesn't use QJson anymore. It uses QJsonBinary which will be included in Qt 5. At the moment I am using backported version for Qt 4.8.

My guess is that linker (when building .so) didn't include QJsonBinary objects so that's why you'll get undefined reference.

Could be bad .pro files. I will look into it.

**Comment by minimoog** [comment]
Ouch, cmake project files are not updated in the latest repository. That's why you are getting undefined references for QJsonBinary.

**Comment by jefferai** [comment]
I didn't update the CMake files since the API/files names/etc. were unstable. Once things are settled I'll be happy to get them updated.

I know it doesn't use QJson anymore, but he didn't specify he was using as opposed to a released version  :-)

**Comment by ghost** [comment]
Ok, now I know what is the problem. As you can see from my commits I've used another library to get things to work, although this was just for a test. Your lib looks a lot simpler, so, once you update it I'll certainly use it :)
