### ISSUE TITLE
authorizeXAuth() and authorizePin() in oauthtwitter.h should be slots

### ISSUE THREAD

**Issue by iamakulov** [minimoog/QTweetLib#19]
Sometimes it's useful to call that functions directly using signal-slot system, without creating the separated slot to call authorizePin(). For example, it's when a pin-dialog and a twitter auth class (wrapper for the OAuthTwitter class) are separated from each other.

**Comment by minimoog** [comment]
Fix pushed on Qt5 branch. Sorry for delay.
