### ISSUE TITLE
it should be possible to give consumer_key and consumer_secret to the OAuth object

### ISSUE THREAD

**Issue by tamasd** [minimoog/QTweetLib#4]
I think it would be a good idea for the OAuth object to get CONSUMER_KEY and CONSUMER_SECRET in its constructor, and use the defined CONSUMER_KEY and CONSUMER_SECRET as a default (fallback) value.

**Comment by minimoog** [comment]
Let me think it through this week, otherwise I liked it. :)

**Comment by minimoog** [comment]
I just added your suggestion. Is it ok now?

**Comment by tamasd** [comment]
Seems fine, however I don't have time to try it out right now.
