### ISSUE TITLE
PIN based OAuth would be great

### ISSUE THREAD

**Issue by kriwil** [minimoog/QTweetLib#5]
PIN based OAuth would be great because I prefer that to xauth :)

**Comment by minimoog** [comment]
Big sorry for the delay... I was busy.

PIN based OAuth support is added. Override OAuthTwitter::authorizationWidget() to show widget where users enters PIN number and return the entered PIN. If you want to show another browser override OAuthTwitter::requestAuthorization().

Not tested. :) Please test it and tell me if it's working and to close the issue.

**Comment by jefferai** [comment]
It's working for us.

**Comment by minimoog** [comment]
Of course it's working! 

There is  even s new example how to use pin oauth.

Best regards,
Toni
