### ISSUE TITLE
Response error:  "Failed to validate oauth signature and token"

### ISSUE THREAD

**Issue by R4md4c** [minimoog/QTweetLib#6]
I have compiled the statusupdate example after making changes to Consumer key, Consumer secret, Token and Token secret. 
When i run the program and enter the username and password and click authorize :
Network Error:  204 
Response error:  "Failed to validate oauth signature and token"

And the status bar says "xAuth Failed".

Why did that happen ?

**Comment by minimoog** [comment]
statusupdate example is wrong. Some errored commit which was test case, there is even some tokens in the code. :)

Remove line 53, 54, 55 from mainwindow.cpp and let me know if it works. You don't need token and token secret.

Don't set token and token secret if you want xauth authorization. Xauth authorization process will give you those token and token secret. You can save them for later use (users don't need to enter username and password).

If you set token and token secret you don't need XAuth authorization process.

**Comment by R4md4c** [comment]
I removed the lines you said to remove but still the same issue resides,

**Comment by minimoog** [comment]
You have XAuth approval from Twitter?

**Comment by R4md4c** [comment]
Sorry but i am new to XAuth/OAuth things.
What i did do is registering my app on dev.twitter.com and got the consumer key and consumer secret.
 is that you mean by XAuth approval ?

**Comment by minimoog** [comment]
With that you got only OAuth approval.  You can use PIN based OAuth, for XAuth see http://dev.twitter.com/pages/xauth

**Comment by semlanik** [comment]
HI, i've tried to use you API and implement my own variant of some parts of API, but have same problem. If I right understand, with xAuth we can only skip token request part. But I see that you implement it. So it still does not work and my implementation to (
