### ISSUE TITLE
QTweetUserStatusesFollowers list size

### ISSUE THREAD

**Issue by emrahkaya** [minimoog/QTweetLib#7]
The QTweetUserStatusesFollowers class gets 100 followers at a time. It would be great if we would set the size of this list.

**Comment by minimoog** [comment]
That's twitter api limit see http://dev.twitter.com/doc/get/statuses/followers . You cannot ask for exact number of followers. In practice usually you fetch them all. 

If you want to fetch them all, you can chain followersFinished slot. For code example see examples/followers/followerslistmodel.cpp , fetchFollowers fetches one page of followers, with followersFinished who checks the cursor, if it's not '0' then again call fetchFollowers until cursor is '0'.

**Comment by emrahkaya** [comment]
Thank you for quick reply. I have noticed the paging support. In fact i wanted to get less than 100 elements. I have made a workaround for this by using an inner list that holds the 100 elements. I take elements from this list. As this gets empty I make another request for thr next page.
Very useful library, by the way.
